/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Forms;

import Dbcon.Database;
import Dbcon.Dbprocess;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    public boolean phoneCheck(String phone) {
        boolean flag = false;
        if (phone.length() != 12 && phone.length() != 10) {
            flag = false;
        } else {
            flag = true;
        }

        return flag;

    }

    public boolean emailCheck(String eml) {
        boolean flag = true;
        int at = eml.indexOf("@");
        int dot = eml.indexOf(".");
        if (at == -1) {
            flag = false;
        }
        if (dot == -1) {
            flag = false;
        }

        if (!(at == eml.lastIndexOf("@"))) {
            flag = false;
        }
        if (!(dot == eml.lastIndexOf("."))) {
            flag = false;
        }
        String s = eml.substring(dot + 1, eml.length());
        System.out.println(s);

        if (s.length() != 3 && s.length() != 2) {
            flag = false;
        }

        return flag;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 360, 46);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 100, 130, 14);

        jLabel3.setText("User Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 140, 150, 14);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 180, 140, 14);

        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 220, 160, 14);

        jLabel6.setText("Email_ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 260, 140, 14);

        jLabel7.setText("Location");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 300, 110, 14);

        jLabel8.setText("Job");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 340, 100, 14);

        jLabel9.setText("Phone Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 380, 100, 14);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 440, 120, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 440, 110, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 100, 130, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(340, 130, 130, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(340, 170, 130, 20);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(340, 210, 130, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(340, 260, 130, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 300, 130, 20);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(340, 340, 130, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(340, 380, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            boolean f = false, f1 = true, f2 = true, f3 = true, f4 = true;
            String n = jTextField1.getText();
            String un = jTextField2.getText();
            String pwd = jPasswordField1.getText();
            String cpwd = jPasswordField2.getText();
            String email = jTextField3.getText();
            String loc = jTextField4.getText();
            String dept = jTextField5.getText();
            final String phone = jTextField6.getText();
            Dbprocess ob = new Dbprocess();



            if (n.equals("") || un.equals("") || pwd.equals("") || cpwd.equals("") || email.equals("") || loc.equals("") || dept.equals("") || phone.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Please fill data in all fields");
                f4 = false;
            } else {
                if (!pwd.equals(cpwd)) {
                    JOptionPane.showMessageDialog(rootPane, "Please check new password and confirm password");
                    f1 = false;
                }


              else  if (!emailCheck(email)) {
                    JOptionPane.showMessageDialog(rootPane, "Emailid is not valid ");
                    f2 = false;
                }
                //else {
               else if (!phoneCheck(phone)) {
                    JOptionPane.showMessageDialog(rootPane, "Phone number is not valid ");
                    f3 = false;
                }
                //                     else {

//

                //}
                //  }
            }
            System.out.println("f1" + f1);
            System.out.println("f2" + f2);
            System.out.println("f3" + f3);
            System.out.println("f4" + f4);
            if (f1 == true && f2 == true && f3 == true && f4 == true) {
                //  boolean g = ob.log(un, pwd, "user", "1");


                Database db = new Database();
                String sql = "select uname from login where uname='" + un + "'";
                ResultSet rs = db.getData(sql);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "username exists......  ");
                } else {
                    String sql1 = "insert into login(uname,upass,utype,status,access,ip,host) values('" + un + "','" + pwd + "','user','1','Active','na','na')";
                    System.out.println(sql1);
                       int i = db.putData(sql1);
                    String id = "select max(id) from login";
                    ResultSet ids = db.getData(id);
                    ids.next();
                 
                    String sql2 = "insert into register values(" + ids.getInt(1) + ",'" + n + "','" + email + "','" + loc + "','" + dept + "','" + phone + "')";
                    System.out.println(sql2);
                    int j = db.putData(sql2);
                    if (i > 0 && j > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Successfully Inserted");
                        //new Adminlogin().setVisible(true);
                        this.setVisible(false);
                        new Login().setVisible(true);
                    }
                }
            }
        } catch (Exception ex) {


            ex.printStackTrace();
        }
        //}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //  new Adminlogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        jTextField6.addKeyListener(new KeyAdapter() {

            public void keyPressed(KeyEvent EVT) {
                String phone = jTextField6.getText();
                int l = phone.length();
                if (EVT.getKeyChar() >= '0' && EVT.getKeyChar() <= '9') {
                    jTextField6.setEditable(true);
                } else {
                    // j_phone.setEditable(false);
                    JOptionPane.showMessageDialog(rootPane, "Please enter numeric values");
                }

            }
        });
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased

        // TODO add your handling code here:
        jTextField6.addKeyListener(new KeyAdapter() {

            public void keyPressed(KeyEvent EVT) {
//                      String phone = j_phone.getText();
//               int l=phone.length();
//               if(EVT.getKeyChar()>='0'&& EVT.getKeyChar()<='9'){
//                   j_phone.setEditable(true);
//               }
//               else{
//                  // j_phone.setEditable(false);
//                    JOptionPane.showMessageDialog(rootPane, "Please enter numeric values");
//               }
            }
        });
    }//GEN-LAST:event_jTextField6KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
