/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Forms;

import Dbcon.Database;
import Network.ReceiverServer;



import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;


/**
 *
 * @author user
 */
public class Userhome extends javax.swing.JFrame {

    public static String stat = "";

    /** Creates new form Userhome */
    public Userhome() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
           uname.setText("Welcome "+Login.cuname);
           new ReceiverServer().start();
            String projectpath = new java.io.File(".").getCanonicalPath();
            String encpath = projectpath + File.separator + "work" + File.separator + "dec" + File.separator;
            String decpath = projectpath + File.separator + "work" + File.separator + "enc" + File.separator;
            String sppath = projectpath + File.separator + "work" + File.separator + "join" + File.separator;
            String dsplit = projectpath + File.separator + "work" + File.separator + "rsplit" + File.separator;
            String ssgn = projectpath + File.separator + "work" + File.separator + "sign" + File.separator;
            String ssplit = projectpath + File.separator + "work" + File.separator + "split" + File.separator;
            String dverify = projectpath + File.separator + "work" + File.separator + "verify" + File.separator;
            File f = new File(encpath);
            File f1 = new File(decpath);
            File f2 = new File(sppath);
            File f4 = new File(dsplit);
            File f5 = new File(ssgn);
            File f6 = new File(ssplit);
            File f3 = new File(dverify);
            if (!f.exists()) {
                f.mkdirs();
            }
            if (!f1.exists()) {
                f1.mkdirs();
            }
            if (!f2.exists()) {
                f2.mkdirs();
            }
            if (!f3.exists()) {
                f3.mkdirs();
            }
            if (!f4.exists()) {
                f4.mkdirs();
            }
            if (!f5.exists()) {
                f5.mkdirs();
            }
            if (!f6.exists()) {
                f6.mkdirs();
            }

        } catch (IOException ex) {
            Logger.getLogger(Userhome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uname = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 380));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        uname.setFont(new java.awt.Font("Tahoma", 1, 15));
        uname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(uname);
        uname.setBounds(60, 10, 120, 20);

        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/encryption.jpg")));
        getContentPane().add(back);
        back.setBounds(0, 0, 280, 324);

        jMenu1.setText("File");

        jMenuItem1.setText("Send Message");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        jMenuItem3.setText("Online Clients");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Settings");

        jMenuItem5.setText("Change Password");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try { 
            String un = Login.cuname;

        String sql = "update login set status='0' where uname='" + un + "'";

        Database db = new Database();
        db.putData(sql);
        ReceiverServer.socket.close();

        this.setVisible(false);
        new Login().setVisible(true);
            
        } catch (Exception e) {
        }
       
        //new Adminlogin().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new SendMessage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String un = Login.cuname;

        String sql = "update login set status='0' where uname='" + un + "'";

        Database db = new Database();
        db.putData(sql);
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Onlineclients().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new Changepassword().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Userhome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables
}
