package forms;

import Db.DBConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Welcome
 */
public class usermanagement extends javax.swing.JFrame {

    /** Creates new form usermanagement */
    String fn = "", ln = "", ph = "", d = "", uname = "", st = "", email = "", id = "";

    public usermanagement() {
        initComponents();
        setLocationRelativeTo(null);
        loadtable();
    }

    void loadtable() {
        try {
            ArrayList<String> id = new ArrayList<String>();
            ArrayList<String> fname = new ArrayList<String>();
            ArrayList<String> lname = new ArrayList<String>();
            ArrayList<String> phno = new ArrayList<String>();
            ArrayList<String> dob = new ArrayList<String>();
            ArrayList<String> username = new ArrayList<String>();
            ArrayList<String> status = new ArrayList<String>();

            String sql = "select register.*,login.access,login.id from login inner join register on register.id=login.id";

            System.out.println(sql);
            DBConnect db = new DBConnect();
            ResultSet rs = db.ReadData(sql);
            while (rs.next()) {
                id.add(rs.getString(1));
                fname.add(rs.getString(2));
                lname.add(rs.getString(3));
                phno.add(rs.getString(4));
                dob.add(rs.getString(5));
                username.add(rs.getString(6));
                status.add(rs.getString("access"));


            }
            DefaultTableModel dtm = (DefaultTableModel) t_users.getModel();
            dtm.setRowCount(fname.size());
            for (int i = 0; i < fname.size(); i++) {

                dtm.setValueAt(id.get(i), i, 0);
                dtm.setValueAt(fname.get(i), i, 1);
                dtm.setValueAt(lname.get(i), i, 2);
                dtm.setValueAt(phno.get(i), i, 3);
                dtm.setValueAt(dob.get(i), i, 4);
                dtm.setValueAt(username.get(i), i, 5);
                dtm.setValueAt(status.get(i), i, 6);


            }
        } catch (SQLException ex) {
            Logger.getLogger(usermanagement.class.getName()).log(Level.SEVERE, null, ex);
        }



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_users = new javax.swing.JTable();
        bt_block = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        t_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Location", "Department", "Phone", "Accessibility"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_users);

        bt_block.setText("ChangeAccessibility");
        bt_block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_blockActionPerformed(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(bt_block, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_block, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_usersMouseClicked
        // TODO add your handling code here:
        int row = t_users.getSelectedRow();
        id = t_users.getValueAt(row, 0).toString();
        fn = t_users.getValueAt(row, 1).toString();
        ln = t_users.getValueAt(row, 2).toString();
        ph = t_users.getValueAt(row, 3).toString();
        d = t_users.getValueAt(row, 4).toString();
        uname = t_users.getValueAt(row, 5).toString();
        st = t_users.getValueAt(row, 6).toString();
        


    }//GEN-LAST:event_t_usersMouseClicked

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        if (fn.equals("") || ln.equals("") || ph.equals("") || d.equals("") || uname.equals("") || st.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "No row selected");
        } else {
            //try {

            DBConnect db = new DBConnect();

            String sql = "delete from login where id='" + id + "'";
            db.ins_upd_del(sql);
            // } catch (SQLException ex) {
            //Logger.getLogger(usermanagement.class.getName()).log(Level.SEVERE, null, ex);
            // }
            loadtable();
        }

    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_blockActionPerformed
        // TODO add your handling code here:
        if (fn.equals("") || ln.equals("") || ph.equals("") || d.equals("") || uname.equals("") || st.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "No row selected");
        } else {
            System.out.println(st);
            if (st.contains("Active")) {
                // try {

                String sql = "update login set access='Blocked' where id='" + id + "'";
                DBConnect db = new DBConnect();
                db.ins_upd_del(sql);
                // } catch (SQLException ex) {
                //   Logger.getLogger(usermanagement.class.getName()).log(Level.SEVERE, null, ex);
                //}

            } else {
                // try {
                int a = 1;
                String sql = "update login set access='Active' where id='" + id + "'";
                DBConnect db = new DBConnect();
                db.ins_upd_del(sql);
                // } catch (SQLException ex) {
                //   Logger.getLogger(usermanagement.class.getName()).log(Level.SEVERE, null, ex);
                //}

            }
        }
        loadtable();
    }//GEN-LAST:event_bt_blockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new usermanagement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_block;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_delete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_users;
    // End of variables declaration//GEN-END:variables
}
